server:
  port: 8081
  servlet:
    context-path: /api/


application:
  jwt:
    secretKey: SecuritySecuritySecuritySecuritySecuritySecuritySecurity
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 1


spring:
  data:
    mongodb:
      uri: mongodb+srv://vihanga:malisha1996@applicationframeork.q7rvl.mongodb.net/ssd?retryWrites=true&w=majority




